### ISSUE TITLE
Function for set universe

### ISSUE THREAD

**Issue by tresler** [sstaub/sACN#7]
Is it possible to add new function for set universe (before begin)? It will be useful if I read universe from EEPROM. Something like that: 

```
void Receiver::setUniverse(uint16_t universe) {
	this->universe = universe;
	mcastIP[2] = universe >> 8;
	mcastIP[3] = universe;
	**}**
```

**Comment by sstaub** [comment]
I think it is possible to do THE class definition in setup() after you read data from the EEPROM.

**Comment by sstaub** [comment]
This will changed in the next release.  e.g. 
```cpp
Receiver(UDP& udp);
begin(uint16_t universe, bool unicastMode = false);
```

**Comment by sstaub** [comment]
Done with v1.1
